// client/src/components/SectorsList.js

// Original list of sectors (with duplicates)
const sectors = [
  "Red Zone",
  "Pakistan Secretariat",
  "Diplomatic Enclave",
  "B-sectors",
  "B-17",
  "C-sectors",
  "C-14",
  "C-15",
  "D-sectors",
  "D-12",
  "D-17",
  "E-sectors",
  "Sector E-9",
  "Sector E-9",
  "Air University, E-9",
  "Air University, E-9",
  "E-7",
  "E-8",
  "E-9",
  "E-10",
  "E-11",
  "E-12",
  "E-16",
  "E-17",
  "F-sectors",
  "Aiwan e Quaid, F-9",
  "Aiwan e Quaid, F-9",
  "Fatima Jinnah Park, F-9",
  "Fatima Jinnah Park, F-9",
  "F-5",
  "F-6",
  "F-7",
  "Jinnah Convention Centre, F-7",
  "Super Market, F-6",
  "F-8",
  "Fatima Jinnah Park ( F-9 Park)",
  "F-10",
  "F-11",
  "F-12",
  "F-15",
  "F-17",
  "G-sectors",
  "A multipurpose sports facility (G-5)",
  "Aabpara Market (G-6)",
  "Karachi Company (G-9)",
  "G-9 Markaz",
  "G-9",
  "G-13",
  "G-13",
  "Ramna-4 Diplomatic Enclave(G-4)",
  "Ramna-5 Diplomatic Enclave(G-5)",
  "G-5",
  "G-6",
  "G-7",
  "G-8",
  "G-9",
  "G-10",
  "G-11",
  "G-12",
  "G-13",
  "G-14",
  "G-15",
  "G-16",
  "H-sectors",
  "Riphah Knowledge Park, H-8",
  "Riphah Knowledge Park, H-8",
  "International Islamic University, H9",
  "International Islamic University, H9",
  "National University of Computer and Emerging Sciences, H-11",
  "National University of Computer and Emerging Sciences, H-11",
  "National University of Sciences and Technology, H-12",
  "National University of Sciences and Technology, H-12",
  "H-8",
  "H-9",
  "International Islamic University Islamabad(IIUI H-10)",
  "H-11",
  "National University of Science and Technology(NUST H-12)",
  "H-13",
  "I-sectors",
  "I-8 Markaz",
  "I-8 Markaz",
  "Fruit and Vegetable Market, I-11",
  "Fruit and Vegetable Market, I-11",
  "I-8",
  "I-9",
  "I-10",
  "I-11",
  "I-12",
  "I-13",
  "I-14",
  "I-15",
  "I-16",
];

// Remove duplicates and sort alphabetically (case-insensitive)
const sectorsList = Array.from(new Set(sectors)).sort((a, b) =>
  a.toLowerCase().localeCompare(b.toLowerCase())
);

export { sectorsList };
